### ISSUE TITLE
API > Submit a new policy

### ISSUE THREAD

**Issue by kdutia** [climatepolicyradar/navigator#11]
@chrisaballard commented on [Tue Dec 07 2021](https://github.com/climatepolicyradar/policy-search/issues/136)

Create a REST api that a new policy can be submitted to. This should support a POST request.

- [x] Define structure of POST request
- [x] Create API
  - [x] document upload API
  - [x] action submission API
- [x] Write tests (including mocking s3)
- [x] Document API using OPENAPI json - this should be visible using the fastapi documentation support
- [x] Return a response indicating that policy has been submitted, or an error has occurred

---

@kdutia commented on [Thu Dec 16 2021](https://github.com/climatepolicyradar/policy-search/issues/136#issuecomment-995609383)

@chrisaballard @eurolife here's a draft of the POST request structure (first point above) for your review https://www.notion.so/climatepolicyradar/Policy-submission-API-design-585004266c064fa8b0d5cb9e8bbba6ce

**Comment by eurolife** [comment]
@kdutia 
Issues/comments on the api:

- Can’t send null values for month/day so sending 1 and 1 until backend can handle null values.
- Looks like there is a file size limit, but not sure what it is or where it’s set. 
- Submit document error - looks like it could be issue with s3 and credentials (error log below)
- fyi: I changed ACCESS_TOKEN_EXPIRE_MINUTES to 300 (security.py) instead of 30 so I don’t have to keep renewing it - not pushing this change though in case we need to keep it at 30.

`INFO:     172.19.0.5:36244 - "POST /api/v1/document HTTP/1.0" 500 Internal Server Error

ERROR:    Exception in ASGI application

Traceback (most recent call last):

  File "/usr/local/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 389, in run_asgi

    result = await app(self.scope, self.receive, self.send)

  File "/usr/local/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__

    return await self.app(scope, receive, send)

  File "/usr/local/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__

    await super().__call__(scope, receive, send)

  File "/usr/local/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__

    await self.middleware_stack(scope, receive, send)

  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__

    raise exc

  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__

    await self.app(scope, receive, _send)

  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 57, in __call__

    task_group.cancel_scope.cancel()

  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 574, in __aexit__

    raise exceptions[0]

  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/base.py", line 30, in coro

    await self.app(scope, request.receive, send_stream.send)

  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 92, in __call__

    await self.simple_response(scope, receive, send, request_headers=headers)

  File "/usr/local/lib/python3.8/site-packages/starlette/middleware/cors.py", line 147, in simple_response

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__

    raise exc

  File "/usr/local/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__

    await self.app(scope, receive, sender)

  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 656, in __call__

    await route.handle(scope, receive, send)

  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 259, in handle

    await self.app(scope, receive, send)

  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 61, in app

    response = await func(request)

  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app

    raw_response = await run_endpoint_function(

  File "/usr/local/lib/python3.8/site-packages/fastapi/routing.py", line 161, in run_endpoint_function

    return await run_in_threadpool(dependant.call, **values)

  File "/usr/local/lib/python3.8/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool

    return await anyio.to_thread.run_sync(func, *args)

  File "/usr/local/lib/python3.8/site-packages/anyio/to_thread.py", line 28, in run_sync

    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,

  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread

    return await future

  File "/usr/local/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 754, in run

    result = context.run(func, *args)

  File "/app/app/api/api_v1/routers/documents.py", line 30, in document_upload

    s3_document = s3_client.upload_fileobj(

  File "/app/app/core/aws.py", line 63, in upload_fileobj

    self.client.upload_fileobj(fileobj, bucket, key)

  File "/usr/local/lib/python3.8/site-packages/boto3/s3/inject.py", line 540, in upload_fileobj

    return future.result()

  File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 106, in result

    return self._coordinator.result()

  File "/usr/local/lib/python3.8/site-packages/s3transfer/futures.py", line 265, in result

    raise self._exception

  File "/usr/local/lib/python3.8/site-packages/s3transfer/tasks.py", line 126, in __call__

    return self._execute_main(kwargs)

  File "/usr/local/lib/python3.8/site-packages/s3transfer/tasks.py", line 150, in _execute_main

    return_value = self._main(**kwargs)

  File "/usr/local/lib/python3.8/site-packages/s3transfer/upload.py", line 694, in _main

    client.put_object(Bucket=bucket, Key=key, Body=body, **extra_args)

  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 391, in _api_call

    return self._make_api_call(operation_name, kwargs)

  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 705, in _make_api_call

    http, parsed_response = self._make_request(

  File "/usr/local/lib/python3.8/site-packages/botocore/client.py", line 725, in _make_request

    return self._endpoint.make_request(operation_model, request_dict)

  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 104, in make_request

    return self._send_request(request_dict, operation_model)

  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 134, in _send_request

    request = self.create_request(request_dict, operation_model)

  File "/usr/local/lib/python3.8/site-packages/botocore/endpoint.py", line 117, in create_request

    self._event_emitter.emit(event_name, request=request,

  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 357, in emit

    return self._emitter.emit(aliased_event_name, **kwargs)

  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 228, in emit

    return self._emit(event_name, kwargs)

  File "/usr/local/lib/python3.8/site-packages/botocore/hooks.py", line 211, in _emit

    response = handler(**kwargs)

  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 93, in handler

    return self.sign(operation_name, request)

  File "/usr/local/lib/python3.8/site-packages/botocore/signers.py", line 165, in sign

    auth.add_auth(request)

  File "/usr/local/lib/python3.8/site-packages/botocore/auth.py", line 378, in add_auth

    raise NoCredentialsError()

botocore.exceptions.NoCredentialsError: Unable to locate credentials`
