### ISSUE TITLE
Decouple loader from stack initialisation

### ISSUE THREAD

**Issue by opyate** [climatepolicyradar/navigator#404]
Currently, we have a catch 22 where the loader starts up before migrations run (after deleting volumes), and loader fails by not finding geographies.

Loader will be moved to a separate task, and not run immediately as part of stack startup.

**Comment by opyate** [comment]
New command: 
```
make run_loader
```

It will fail like this if the backend database has issues:


```
$ make run_loader
docker-compose -f docker-compose.yml -f docker-compose.dev.yml run --rm loader python app/main.py
Creating navigator_loader_run ... done
Traceback (most recent call last):
  File "/app/app/main.py", line 75, in <module>
    main()
  File "/app/app/main.py", line 63, in main
    load(policies)
  File "/app/app/load/main.py", line 17, in load
    geography_id = get_geography_id(country_code)
  File "/app/app/load/api_client.py", line 20, in get_geography_id
    return _get_id(country_code, get_geographies_lookup, "geography_id")
  File "/app/app/load/api_client.py", line 45, in _get_id
    lookup = lookup_fn()
  File "/app/app/load/api_client.py", line 18, in 
get_geographies_lookup
    return _get_lookup("geographies", "country_code")
  File "/app/app/load/api_client.py", line 69, in _get_lookup
    raise Exception(
Exception: Backend error. Check migrations ran, or base data is imported (e.g. geographies)
make: *** [makefile-docker.defs:70: run_loader] Error 1

```

Note error 
> Exception: Backend error. Check migrations ran, or base data is imported (e.g. geographies)
